---
title: "Analyze RMSE and SD of Predictions"
author: "Joel Carlson"
date: "June 29, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "../")
```
```{r, message=FALSE, warning=FALSE}
library(reshape2); library(dplyr); library(ggplot2); library(lazyeval)
```

In this document I explore the predictive accuracy of the models as they predict further into the future.

```{r, message=FALSE, cache=TRUE}
source("scripts/extract_RMSE_SD_from_predictions.R")
source("scripts/extract_RMSE_SD_from_trend_predictions.R")
base_path <- "data/temp/"
testing_paths_1Br <- list.files(base_path, pattern="MRP_1Br_testing")


MRP_1Br_RMSE <- extract_testing_RMSE_SD("MRP_1Br_MoM", testing_paths_1Br)
MRP_1Br_trend_RMSE <- extract_testing_trend_RMSE_SD_MRP_1Br(file_paths)

MRP_1Br_RMSE$date <- as.Date(MRP_1Br_RMSE$date)
MRP_1Br_trend_RMSE$date <- as.Date(MRP_1Br_trend_RMSE$date)

```

# MRP 1Br Month over Month 

````{r}
MRP_1Br_RMSE$months_in_future <- cut(as.numeric(MRP_1Br_RMSE$days_in_future),
                                     breaks=seq(from=1, to=365, length.out=13),
                                     labels=c(1:12))

MRP_1Br_RMSE_plt_dat <- MRP_1Br_RMSE %>% select(date, days_in_future, months_in_future, naive_RMSE, rf_RMSE, full_rf_RMSE) %>% melt(id.vars=c("date", "days_in_future", "months_in_future"))

ggplot(data=filter(MRP_1Br_RMSE_plt_dat, days_in_future <= 365),
       aes(x=months_in_future, y=value, group=months_in_future, fill=variable)) +
  geom_boxplot() +
  guides(fill=FALSE) +
  facet_wrap(~variable)
  #scale_color_viridis(discrete = TRUE)
```

```{r}
MRP_1Br_RMSE_plt_dat <- MRP_1Br_RMSE %>% select(date, days_in_future, months_in_future, naive_SD, rf_SD, full_rf_SD) %>% melt(id.vars=c("date", "days_in_future", "months_in_future"))

ggplot(data=filter(MRP_1Br_RMSE_plt_dat, days_in_future <= 365),
       aes(x=months_in_future, y=value, group=months_in_future, fill=variable)) +
  geom_boxplot() +
  guides(fill=FALSE) +
  facet_wrap(~variable)
```

# MRP 1Br Trend Prediction

```{r, warning=FALSE}

MRP_1Br_trend_RMSE$months_in_future <- cut(as.numeric(MRP_1Br_trend_RMSE$days_in_future),
                                            breaks=seq(from=1, to=365, length.out=13),
                                            labels=c(1:12))

MRP_1Br_trend_RMSE_plt_dat <- MRP_1Br_trend_RMSE %>% select(date, days_in_future, months_in_future, naive_trend_RMSE, rf_trend_RMSE, full_rf_trend_RMSE) %>% melt(id.vars=c("date", "days_in_future", "months_in_future"))

ggplot(data=filter(MRP_1Br_trend_RMSE_plt_dat, days_in_future <= 365),
       aes(x=months_in_future, y=value, group=months_in_future, fill=variable)) +
  geom_boxplot() +
  guides(fill=FALSE) +
  facet_wrap(~variable)
```
